namespace: prod
namePrefix: prod-
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: web
  - patch: |-
      - op: replace
        path: /data/index.html
        value: |
          <html>
          <body>
          <h1>PROD</h1>
          </body>
          </html>
    target:
      kind: ConfigMap
      name: web-content
